disabled = false
locale = "en"
label = "English"
weight = 2
title = "Daigo Suhara"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "The portfolio of Daigo Suhara."
  copyright = "© { year } Daigo Suhara"
  dateFormat = "2 January 2006"

[params.author]
  name = "Daigo Suhara"
  headline = "Graduate Student"
  image = "img/avatar.webp"
  bio = "I conduct research on Human-Robot Interaction at Kansai University Graduate School."
   links = [
     { github = "https://github.com/daigo-suhara" },
     { x-twitter = "https://x.com/daigo_suhara" },
     { email = "mailto:suharadaigo@gmail.com" }
   ]
