[[main]]
  name = "Blog"
  identifier = "blog"
  pre = "pencil"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "All Posts"
  pageRef = "blog"
  parent = "blog"
  weight = 11

[[main]]
  name = "Categories"
  pageRef = "categories"
  parent = "blog"
  weight = 12

[[main]]
  name = "Tags"
  pageRef = "tags"
  parent = "blog"
  weight = 13

[[main]]
  name = "Work"
  pre = "code"
  pageRef = "work"
  weight = 20

[[main]]
  name = "Gallery"
  identifier = "gallery"
  pre = "image"
  weight = 25

[[main]]
  name = "2026"
  pageRef = "photos/2026"
  parent = "gallery"
  weight = 26

[[main]]
  name = "About"
  pre = "circle-info"
  pageRef = "about"
  weight = 30
