[[main]]
  name = "Blog"
  pre = "pencil"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Work"
  pre = "code"
  pageRef = "work"
  weight = 20

[[main]]
  name = "About"
  pre = "circle-info"
  pageRef = "profile"
  weight = 30
